### ISSUE TITLE
eslint-plugin-n should be dependency

### ISSUE THREAD

**Issue by evoactivity** [NullVoxPopuli/ember-eslint#1]
Tried to set this up, eslint-plugin-n is listed as a devDependency so doesn't get installed. 
`pnpm why eslint-plugin-n` returns nothing.

I tried patching the package.json but that doesn't help.

Lockfile looks like this

```
  ember-eslint@0.0.1(@babel/core@7.26.7)(@typescript-eslint/parser@8.23.0(eslint@9.19.0(jiti@1.21.7))(typescript@5.5.4))(eslint@9.19.0(jiti@1.21.7))(typescript@5.5.4):
    dependencies:
      '@babel/eslint-parser': 7.26.5(@babel/core@7.26.7)(eslint@9.19.0(jiti@1.21.7))
      '@eslint/js': 9.19.0
      eslint-config-prettier: 10.0.1(eslint@9.19.0(jiti@1.21.7))
      eslint-plugin-ember: 12.5.0(@babel/core@7.26.7)(@typescript-eslint/parser@8.23.0(eslint@9.19.0(jiti@1.21.7))(typescript@5.5.4))(eslint@9.19.0(jiti@1.21.7))
      eslint-plugin-qunit: 8.1.2(eslint@9.19.0(jiti@1.21.7))
      typescript-eslint: 8.23.0(eslint@9.19.0(jiti@1.21.7))(typescript@5.5.4)
    transitivePeerDependencies:
      - '@babel/core'
      - '@typescript-eslint/parser'
      - eslint
      - supports-color
      - typescript
```
